"""Smoke tests for src/constrain/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_constrain_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    assert mod is not None

def test_ensure_api_key_is_callable():
    """Function ensure_api_key exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "ensure_api_key", None)
    assert fn is not None, "'ensure_api_key' not found in constrain.cli"
    assert callable(fn)

def test_resolve_config_is_callable():
    """Function resolve_config exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "resolve_config", None)
    assert fn is not None, "'resolve_config' not found in constrain.cli"
    assert callable(fn)

def test_cli_is_callable():
    """Function cli exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "cli", None)
    assert fn is not None, "'cli' not found in constrain.cli"
    assert callable(fn)

def test_cmd_new_is_callable():
    """Function cmd_new exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "cmd_new", None)
    assert fn is not None, "'cmd_new' not found in constrain.cli"
    assert callable(fn)

def test_cmd_resume_is_callable():
    """Function cmd_resume exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "cmd_resume", None)
    assert fn is not None, "'cmd_resume' not found in constrain.cli"
    assert callable(fn)

def test_cmd_show_is_callable():
    """Function cmd_show exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "cmd_show", None)
    assert fn is not None, "'cmd_show' not found in constrain.cli"
    assert callable(fn)

def test_cmd_list_is_callable():
    """Function cmd_list exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "cmd_list", None)
    assert fn is not None, "'cmd_list' not found in constrain.cli"
    assert callable(fn)

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in constrain.cli"
    assert callable(fn)
