"""Smoke tests for src/constrain/models.py (auto-generated by pact adopt)."""

import pytest

def test_import_constrain_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("constrain.models")
    assert mod is not None
