"""Smoke tests for src/constrain/synthesizer.py (auto-generated by pact adopt)."""

import pytest

def test_import_constrain_synthesizer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("constrain.synthesizer")
    assert mod is not None

def test_parse_synthesis_output_is_callable():
    """Function parse_synthesis_output exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.synthesizer")
    fn = getattr(mod, "parse_synthesis_output", None)
    assert fn is not None, "'parse_synthesis_output' not found in constrain.synthesizer"
    assert callable(fn)

def test_write_artifacts_is_callable():
    """Function write_artifacts exists and is callable."""
    import importlib
    mod = importlib.import_module("constrain.synthesizer")
    fn = getattr(mod, "write_artifacts", None)
    assert fn is not None, "'write_artifacts' not found in constrain.synthesizer"
    assert callable(fn)
