"""Smoke tests for src/constrain/session.py (auto-generated by pact adopt)."""

import pytest

def test_import_constrain_session():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("constrain.session")
    assert mod is not None
