"""Smoke tests for src/constrain/engine.py (auto-generated by pact adopt)."""

import pytest

def test_import_constrain_engine():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("constrain.engine")
    assert mod is not None
